spring.application.name=receitas-promocao

spring.datasource.url=jdbc:postgresql://localhost/db_teste
spring.datasource.username=postgres
spring.datasource.password=bibi777
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update